/**
* @file Cluster.cc
* @class Cluster
* @brief Define a cluster of points in the detector plane
*
* A Cluster class is created for adhiacent hit points by the TrackFinder class
* A ROOT dictionary for this class is generated by the Makefile
* @author S. Riggi
* @date 25/02/2011
*/

#include "Cluster.hh"
#include <TGeoTrack.h>
#include <TVirtualGeoTrack.h>


Cluster::Cluster()
{

	fPointsDetId.clear();
	fPointsDetId.resize(0);

}//close constructor

Cluster::~Cluster()
{

}//close destructor


ClassImp(Cluster)

#ifdef __MAKECINT__
#pragma link C++ class Cluster+; 
#endif

#ifdef __MAKECINT__
#pragma link C++ class std::vector<Cluster*>+;
#endif

#ifdef __MAKECINT__
#pragma link C++ class std::vector<Cluster>+;
#endif

